# ApartmentIQ Data

1. Pulling all comspet IDs account has access to
2. Pulling all property IDs associated with that account
3. Sending historical data jobs associated with those property IDs
4. Save files to S3
5. Process read into DBT - following build

Note: Notebook on scheduler is set-up differently

# Pulling compset IDs

In [4]:
import os
import sys
import time
import requests
import pandas as pd
from dotenv import load_dotenv

load_dotenv()
TOKEN_URL = "https://data.apartmentiq.io/oauth/token"
BASE_URL = "https://data.apartmentiq.io/apartmentiq/api/v1"
CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRET = os.getenv("CLIENT_SECRET")

session = requests.Session()
session.headers.update({"User-Agent": "apartmentiq-api-client/1.0"})

token = None
token_expires_at = 0

def get_token():
    global token, token_expires_at
    if token and time.time() < token_expires_at:
        return token
    res = session.post(TOKEN_URL, data={
        "grant_type": "client_credentials",
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
    })
    res.raise_for_status()
    data = res.json()
    token = data["access_token"]
    token_expires_at = time.time() + (data["expires_in"] - 60)
    return token

res = session.get(
    f"{BASE_URL}/accounts",
    headers={"Authorization": f"Bearer {get_token()}"},
)
print(res.json())

{'data': [{'id': 9919636, 'name': 'Affinius Capital'}], 'pagination': {'current_page': 1, 'total_pages': 1, 'total_count': 1, 'per_page': 50}}

In [ ]:
headers = {"Authorization": f"Bearer {get_token()}"}

In [9]:
response = res.json()
affinius_id = response['data'][0]['id']

In [10]:
url_listcompset = f"https://data.apartmentiq.io/apartmentiq/api/v1/accounts/{affinius_id}/comp_sets"
response_listcompset = requests.get(url_listcompset, headers=headers)

In [11]:
data_listset = response_listcompset.json()
df_compsetlist = pd.json_normalize(data_listset['data'])
df_compsetlist.columns = df_compsetlist.columns.str.replace('attributes.', '')

In [14]:
df_compsetlist.head(5)

,id,type,id,name,min_floorplan,max_floorplan,category,created_at,value_add,created_user_id,created_user_name,image,show_recommendations_link,market_survey,custom_property,addresses,subject_property_ids,pricing_approval_stage,owned_property_addresses
0,11861923,comp_set,11861923,101 West End Avenue Market,0,4,market_survey,2024-08-06T19:22:18.000Z,None,104789,Alex Field,https://apartmentiq-assets.rentable.co/images/...,False,True,False,"[101 W End Ave, Manhattan, NY 10023]",[99066266],None,"[{'id': 99066266, 'name': '101 West End Avenue..."
1,11861910,comp_set,11861910,1100 South Market,0,3,market_survey,2024-08-06T18:17:18.000Z,None,104789,Alex Field,https://apartmentiq-assets.rentable.co/images/...,False,True,False,"[1100 South Blvd, Charlotte, NC 28203]",[99002185],None,"[{'id': 99002185, 'name': '1100 South Apartmen..."
2,11861909,comp_set,11861909,19Nineteen Market,0,3,market_survey,2024-08-06T18:15:57.000Z,None,104789,Alex Field,https://apartmentiq-assets.rentable.co/images/...,False,True,False,"[1919 Clarendon Blvd, Arlington, VA 22201]",[99065091],None,"[{'id': 99065091, 'name': '19Nineteen', 'addre..."
3,11888181,comp_set,11888181,216 Pico Boulevard Mixed-Use Complex Report,0,3,research_report,2025-06-03T19:24:14.000Z,False,251219,Brian Griffith,https://apartmentiq-assets.rentable.co/6ece930...,False,False,False,[],[],None,[]
4,11861924,comp_set,11861924,220 East 72 Market,0,4,market_survey,2024-08-06T19:24:08.000Z,None,104789,Alex Field,https://apartmentiq-assets.rentable.co/images/...,False,True,False,"[220 E 72nd St, New York, NY 10021]",[99067024],None,"[{'id': 99067024, 'name': '220 East 72nd Stree..."

In [15]:
compset_ids = df_compsetlist['id'].values[:,1]
print(f'No of Compset IDs available: {len(compset_ids)}')

No of Compset IDs available: 114

# Pulling property IDs

For every compset ID, pulling latest unit-level information to find a list of all unique property IDs we have access to - ultimately we are working with unit level data

In [17]:
arr_propids_raw = []
c = 0
for i in compset_ids:
    c+=1
    print(f'Pulling propertiers for compset ID: S. No {c}, ID: {i}')
    url_listunits = f'''https://data.apartmentiq.io/apartmentiq/api/v1/comp_sets/{i}/units'''
    response_unittest = requests.get(url_listunits, headers=headers)
    data_testunit = response_unittest.json()
    units_df = pd.json_normalize(data_testunit['data'])
    units_df.columns = units_df.columns.str.replace('attributes.', '')
    print(f'No of property IDs found for this compset ID: {len(units_df['property_id'].unique())}')
    arr_propids_raw.append(units_df['property_id'].unique())

Pulling propertiers for compset ID: S. No 1, ID: 11861923
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 2, ID: 11861910
No of property IDs found for this compset ID: 14
Pulling propertiers for compset ID: S. No 3, ID: 11861909
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 4, ID: 11888181
No of property IDs found for this compset ID: 3
Pulling propertiers for compset ID: S. No 5, ID: 11861924
No of property IDs found for this compset ID: 4
Pulling propertiers for compset ID: S. No 6, ID: 11928591
No of property IDs found for this compset ID: 11
Pulling propertiers for compset ID: S. No 7, ID: 11918539
No of property IDs found for this compset ID: 9
Pulling propertiers for compset ID: S. No 8, ID: 11861843
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 9, ID: 11884139
No of property IDs found for this compset ID: 12
Pulling propertiers for compset ID: S. No 10, ID: 11902396
No of property IDs found for this compset ID: 12
Pulling propertiers for compset ID: S. No 11, ID: 11905382
No of property IDs found for this compset ID: 9
Pulling propertiers for compset ID: S. No 12, ID: 11902391
No of property IDs found for this compset ID: 12
Pulling propertiers for compset ID: S. No 13, ID: 11905207
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 14, ID: 11902381
No of property IDs found for this compset ID: 6
Pulling propertiers for compset ID: S. No 15, ID: 11861855
No of property IDs found for this compset ID: 13
Pulling propertiers for compset ID: S. No 16, ID: 11917558
No of property IDs found for this compset ID: 9
Pulling propertiers for compset ID: S. No 17, ID: 11902352
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 18, ID: 11942773
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 19, ID: 11861880
No of property IDs found for this compset ID: 14
Pulling propertiers for compset ID: S. No 20, ID: 11861879
No of property IDs found for this compset ID: 13
Pulling propertiers for compset ID: S. No 21, ID: 11861852
No of property IDs found for this compset ID: 6
Pulling propertiers for compset ID: S. No 22, ID: 11923156
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 23, ID: 11861932
No of property IDs found for this compset ID: 12
Pulling propertiers for compset ID: S. No 24, ID: 11942783
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 25, ID: 11861853
No of property IDs found for this compset ID: 6
Pulling propertiers for compset ID: S. No 26, ID: 11861905
No of property IDs found for this compset ID: 12
Pulling propertiers for compset ID: S. No 27, ID: 11887295
No of property IDs found for this compset ID: 13
Pulling propertiers for compset ID: S. No 28, ID: 11902345
No of property IDs found for this compset ID: 5
Pulling propertiers for compset ID: S. No 29, ID: 11902416
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 30, ID: 11861885
No of property IDs found for this compset ID: 5
Pulling propertiers for compset ID: S. No 31, ID: 11897312
No of property IDs found for this compset ID: 2
Pulling propertiers for compset ID: S. No 32, ID: 11905127
No of property IDs found for this compset ID: 6
Pulling propertiers for compset ID: S. No 33, ID: 11861889
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 34, ID: 11905194
No of property IDs found for this compset ID: 9
Pulling propertiers for compset ID: S. No 35, ID: 11911291
No of property IDs found for this compset ID: 6
Pulling propertiers for compset ID: S. No 36, ID: 11902415
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 37, ID: 11861851
No of property IDs found for this compset ID: 6
Pulling propertiers for compset ID: S. No 38, ID: 11861887
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 39, ID: 11861892
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 40, ID: 11861888
No of property IDs found for this compset ID: 13
Pulling propertiers for compset ID: S. No 41, ID: 11861886
No of property IDs found for this compset ID: 12
Pulling propertiers for compset ID: S. No 42, ID: 11861890
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 43, ID: 11942769
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 44, ID: 11910698
No of property IDs found for this compset ID: 6
Pulling propertiers for compset ID: S. No 45, ID: 11911078
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 46, ID: 11911080
No of property IDs found for this compset ID: 9
Pulling propertiers for compset ID: S. No 47, ID: 11942771
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 48, ID: 11882264
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 49, ID: 11881723
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 50, ID: 11902403
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 51, ID: 11861884
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 52, ID: 11861850
No of property IDs found for this compset ID: 9
Pulling propertiers for compset ID: S. No 53, ID: 11861839
No of property IDs found for this compset ID: 9
Pulling propertiers for compset ID: S. No 54, ID: 11861854
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 55, ID: 11917841
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 56, ID: 11861836
No of property IDs found for this compset ID: 13
Pulling propertiers for compset ID: S. No 57, ID: 11861896
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 58, ID: 11919050
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 59, ID: 11926241
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 60, ID: 11861882
No of property IDs found for this compset ID: 12
Pulling propertiers for compset ID: S. No 61, ID: 11907417
No of property IDs found for this compset ID: 6
Pulling propertiers for compset ID: S. No 62, ID: 11905189
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 63, ID: 11942788
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 64, ID: 11912069
No of property IDs found for this compset ID: 2
Pulling propertiers for compset ID: S. No 65, ID: 11861895
No of property IDs found for this compset ID: 15
Pulling propertiers for compset ID: S. No 66, ID: 11861930
No of property IDs found for this compset ID: 14
Pulling propertiers for compset ID: S. No 67, ID: 11861894
No of property IDs found for this compset ID: 17
Pulling propertiers for compset ID: S. No 68, ID: 11861900
No of property IDs found for this compset ID: 13
Pulling propertiers for compset ID: S. No 69, ID: 11861898
No of property IDs found for this compset ID: 12
Pulling propertiers for compset ID: S. No 70, ID: 11861927
No of property IDs found for this compset ID: 11
Pulling propertiers for compset ID: S. No 71, ID: 11938317
No of property IDs found for this compset ID: 6
Pulling propertiers for compset ID: S. No 72, ID: 11861928
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 73, ID: 11902407
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 74, ID: 11906688
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 75, ID: 11942778
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 76, ID: 11942777
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 77, ID: 11910703
No of property IDs found for this compset ID: 4
Pulling propertiers for compset ID: S. No 78, ID: 11913391
No of property IDs found for this compset ID: 1
Pulling propertiers for compset ID: S. No 79, ID: 11942780
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 80, ID: 11942775
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 81, ID: 11881964
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 82, ID: 11942774
No of property IDs found for this compset ID: 9
Pulling propertiers for compset ID: S. No 83, ID: 11942793
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 84, ID: 11910710
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 85, ID: 11912073
No of property IDs found for this compset ID: 1
Pulling propertiers for compset ID: S. No 86, ID: 11861936
No of property IDs found for this compset ID: 9
Pulling propertiers for compset ID: S. No 87, ID: 11861871
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 88, ID: 11861881
No of property IDs found for this compset ID: 13
Pulling propertiers for compset ID: S. No 89, ID: 11861908
No of property IDs found for this compset ID: 13
Pulling propertiers for compset ID: S. No 90, ID: 11861840
No of property IDs found for this compset ID: 14
Pulling propertiers for compset ID: S. No 91, ID: 11861911
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 92, ID: 11902408
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 93, ID: 11942790
No of property IDs found for this compset ID: 5
Pulling propertiers for compset ID: S. No 94, ID: 11910706
No of property IDs found for this compset ID: 2
Pulling propertiers for compset ID: S. No 95, ID: 11861903
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 96, ID: 11886400
No of property IDs found for this compset ID: 2
Pulling propertiers for compset ID: S. No 97, ID: 11861921
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 98, ID: 11910734
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 99, ID: 11892836
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 100, ID: 11861838
No of property IDs found for this compset ID: 12
Pulling propertiers for compset ID: S. No 101, ID: 11861931
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 102, ID: 11888133
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 103, ID: 11899147
No of property IDs found for this compset ID: 16
Pulling propertiers for compset ID: S. No 104, ID: 11902348
No of property IDs found for this compset ID: 7
Pulling propertiers for compset ID: S. No 105, ID: 11908524
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 106, ID: 11926852
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 107, ID: 11905126
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 108, ID: 11885832
No of property IDs found for this compset ID: 6
Pulling propertiers for compset ID: S. No 109, ID: 11905172
No of property IDs found for this compset ID: 10
Pulling propertiers for compset ID: S. No 110, ID: 11861847
No of property IDs found for this compset ID: 9
Pulling propertiers for compset ID: S. No 111, ID: 11902399
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 112, ID: 11942791
No of property IDs found for this compset ID: 8
Pulling propertiers for compset ID: S. No 113, ID: 11861849
No of property IDs found for this compset ID: 6
Pulling propertiers for compset ID: S. No 114, ID: 11861856
No of property IDs found for this compset ID: 3

In [20]:
arr_propids = []
for x in arr_propids_raw:
    arr_propids +=list(x)

print(f'Final total number of Unique property IDs: {len(set(arr_propids))}')

Final total number of Unique property IDs: 787

In [21]:
# Quick note on above result : there are overlapping property IDs for different compsets

In [22]:
arr_propids = list(set(arr_propids))

# Submitting historical batch jobs for all property IDs to fetch unit level rent/features information

APIQ only allows 200 property IDs per job, earliest date for data pull is 1st January, 2020

In [26]:
for i in range(0,len(arr_propids),200):
    url = "https://data.apartmentiq.io/apartmentiq/api/v1/bulk_api/jobs"

    payload = {
        "report_type": "units", #can also be property/floorplan
        "output_format": "csv",
        "start_date": "2025-06-14",
        "end_date": "2026-06-16",
        "property_ids": [int(x) for x in arr_propids[i:min(i+200,len(arr_propids))]]
    }
    headers = {
        "Authorization": f"Bearer {get_token()}",
        "Content-Type": "application/json"
    }
    
    response = requests.post(url, json=payload, headers=headers)
    
    print(response.text)

{"job_id":"d38d0b64-759a-48e8-984b-a13f5209f949","report_type":"units","status":"submitted","output_format":"csv","property_ids":[99061760,99067905,99098627,99084293,99031046,99069959,99067910,99080199,99139595,99078155,99067918,99018768,99018770,99002390,99080224,99078177,99053602,99072035,99014692,99010596,99076133,99078183,99010592,99010593,99045420,99008560,99078199,99033147,100515902,99010624,99012672,99065920,99072069,99168327,99070024,100513872,99084375,99078236,99217500,99070047,100515936,99068001,100208742,99035242,99002474,100341870,99078256,100524146,99002483,99082357,99078262,99141752,99047547,99031167,99078273,99035267,99037316,99002501,99078278,100255883,99029133,99078286,99068045,99068046,99068049,99068050,99129485,99004568,99012761,99006618,99047579,99008669,99008670,99008677,99004585,99082410,99000493,99000494,99020975,99000496,99000497,100214961,99072179,99008692,99078325,99008693,99033273,99047611,99098811,99002557,99039419,99039423,99043525,99104966,99043527,99033292,99047632,99078355,99068116,99043542,99006686,99029227,99043566,99029230,99070193,99082487,99080447,99076356,99008773,99031302,99064069,99064072,99002628,99008776,99078411,99082507,99025167,99082519,99082520,99002647,99078426,99008798,99072287,99045664,99047717,99035131,99078442,100391213,2318638,99006767,100182318,99027254,99064120,99084603,99025212,99004738,99004746,99064145,99000659,99008852,99000660,99008854,99080537,99082585,100237659,99078496,99078497,100204897,99078499,99027300,99078500,99115361,99004775,99084648,99025257,99074409,99000680,99017072,99068278,99076474,99080571,99080573,99008896,99002753,99008900,99080581,99076486,99078536,99078537,99008906,99002761,99076493,99027342,99064211,99004819,99029400,99066266,99008923,99008924,99115419,99035547,100319647,99066273,99068321,100198819,99008942,99084719,99037615,99039229,99019189,99082677,99080635,99111356,99078588,99008957,99033537,99033538,99033540,99033541,99195336],"start_date":"2025-06-14","end_date":"2026-06-16","created_at":"2026-06-17T17:06:03.157Z","updated_at":"2026-06-17T17:06:03.157Z","callback_url":null,"error_message":null}
{"job_id":"4096d6a9-09e7-4b52-9f01-ccfad8a8d7d9","report_type":"units","status":"submitted","output_format":"csv","property_ids":[99078604,99041740,99064272,99008980,99027414,99041757,99078626,99078628,99072484,99377640,99084786,99072499,99004916,99031545,99031546,99004929,99084804,99105285,99078667,100194840,99070493,99068457,100526637,99082799,99111473,99054131,100526643,99011123,99011128,99172924,99080768,99037764,99097157,99078727,99072583,99129928,99019343,99009105,99123793,99074641,99084889,99080794,100516446,99080799,99129952,100526692,100278889,99039853,99068528,99146353,99064437,99068540,100184700,99084927,99084928,99080845,99009165,99465871,99070615,99080856,99080857,99115673,99080855,99084959,99033772,99001004,99127983,99066553,99066555,99066556,99066557,99072699,99066558,99078860,99078861,99078862,99042008,99119843,99037929,99007213,99066610,100233971,99029757,99078912,99083009,99087106,99040003,99005189,100209415,100330249,99044111,99021587,99064596,99003158,99076888,99017500,99001118,99001119,99103521,100223779,99111725,99066671,99072833,100227909,99119946,99033934,99072849,99076946,99001172,99078999,99083097,99079003,99027805,99081054,99005278,99093346,99070820,99066731,99081074,99079030,99079031,99079032,99079035,99066749,99079038,99011455,99081093,99066759,99066761,99083149,99011473,99001233,99017617,99011476,99021715,99023766,100246424,100803481,99066779,99040157,99066782,99007395,99013542,99007406,99027892,100168629,99013557,99066807,99031992,99081145,99023802,99013565,99034045,99001281,99005377,99068868,99130310,99013587,99023829,99070934,99032028,99081182,99034078,99206110,99083232,99021791,99005411,99075045,99021797,99021800,99029992,99029994,99029995,99029996,99083244,99029997,100228079,99029993,99032050,99032053,99064824,99032060,99032062,99206145,99021825,99183622,99081232,99150865,99066898,99066900,99066901,99066904,99017754,99066909,99066912,99046435,99081252,100191273,99206188,99036205],"start_date":"2025-06-14","end_date":"2026-06-16","created_at":"2026-06-17T17:06:03.345Z","updated_at":"2026-06-17T17:06:03.345Z","callback_url":null,"error_message":null}
{"job_id":"006dc292-af1f-4cf7-8d8f-0f99054e284a","report_type":"units","status":"submitted","output_format":"csv","property_ids":[99042349,99206193,99040311,99066939,99081281,99081282,100234306,99036231,99034184,99073100,100516946,99071059,99206229,100514902,99005528,99011677,99114088,99005545,99066988,99015790,99066991,99060848,99066993,99081329,99206257,99021938,99079285,99071088,99060852,99083384,99110010,99067010,99001475,99064964,99001478,99013772,99064974,99064975,99067024,99079312,99067026,99064977,99067028,99077270,99071128,99003549,99013795,99067044,99067046,99067050,99067051,99015851,99081389,99021999,99132594,99126450,99081397,99028157,99087549,99132608,99032258,99089608,99046601,99081419,99013836,99011793,99028179,99087574,99013850,99028186,99077341,99093726,99077342,99032286,99024100,99206373,99024104,99022065,99022067,99011828,99013875,99011830,99013876,99065082,100517115,99093756,99206402,99065091,99071235,99071236,99032334,99032335,99077402,99032347,99077404,100230429,99073307,99018017,100515106,99081508,99032358,99001651,99044660,99046715,99022141,99065149,99077439,99083584,99128640,99079490,99065156,99065157,99106118,100525384,99071310,99013967,99077455,99007825,99077454,99018063,99081556,99032414,99083614,99020129,99138914,99077473,99034472,99013998,100521333,99081598,99071361,99040648,100214155,99085707,99003791,99038610,99032467,99077523,99040668,99007902,99138980,99003813,99067305,100162988,99069358,99001776,99077553,99007921,99083698,99071414,99067320,99014079,99001794,99132867,99077574,99075527,99022278,99071430,99022282,99073481,99067334,99005900,99005903,99083729,99007957,99186136,99151322,99012062,99032543,99067362,99001828,99032549,99012070,99026407,99079661,99106291,100779522,99012102,99079687,99018259,99073561,99081755,99120670,99077663,99001895,99042857,99079724,99006002,99003955,99038773,99081783,100163133,99087937,99083842,99069507,99030596,99067463,99067464,99081800,99030599],"start_date":"2025-06-14","end_date":"2026-06-16","created_at":"2026-06-17T17:06:03.508Z","updated_at":"2026-06-17T17:06:03.508Z","callback_url":null,"error_message":null}
{"job_id":"258a6ce8-89b2-4553-a81e-0fc3fb5531c8","report_type":"units","status":"submitted","output_format":"csv","property_ids":[99067467,99130955,99065421,99071563,99016268,99083856,99016270,100163152,99081813,99003990,99032664,99085918,99077727,99071584,99073632,99014242,100179557,99075685,99030631,99071589,99083881,99001962,100525675,99145329,99006068,99006069,99135098,99114621,99073663,99014272,99073668,99030660,99030666,99083916,99077775,99006097,99030677,99002008,99006107,99131036,99079843,99069604,99126955,99088045,99067572,99067573,99036855,99040953,99002042,99067580,99083965,99067581,100163262,99079874,100779720,99092174,99004112,99006163,100191959,99069655,99077849,99040986,99069657,100179679,99030752,99030753,99030754,99069667,100396770,99079906,100351720,99030761,99018474,99071722,99030764,99030766,99137266,99006195,100335346,99049205,100179705,99069693,99020542,99020541,99020549,100216584,99106568,99006220,99088143,99071760,99061520,100200212,99079962,99131166,99077920,99079970,99004194,100513574,99018540,99018541,99036976,99043122,99022645,99010359,99004216,99041079,100591418,99082039,99065660,99012412,99065662,99075900,99079991,99080001,100177724,99084099,99041092,99084100,99028806,99071815,99036996,99002185,99082057,100527942,99071813,99002190,99024719,99053393,99084117,99080021,99071829,99016536,99174238,99016549,99067765,99082112,99069827,99067780,99067781,99004293,99094410,100185995,99067789,99002255,99082130,99166099,99123095,99049368,99076002,99004323,99104679,99076008,99071917,99065776,99033015,99026871,99014585,99002298,99082171,99078079,99065797,99065798,99065799,99065800,99030989,99030990,99039182,99080145,99016660,99074006,99080153,99071963,99067868,99074017,99033058,99078115,99031012,99047397,99031014,99002349,99031022,99020785,99076090,99045371,99045372,99043325,99031039],"start_date":"2025-06-14","end_date":"2026-06-16","created_at":"2026-06-17T17:06:03.593Z","updated_at":"2026-06-17T17:06:03.593Z","callback_url":null,"error_message":null}

## Listing JOB IDs

In [30]:
url_listjobs = "https://data.apartmentiq.io/apartmentiq/api/v1/bulk_api/jobs?page=1&per_page=50"
headers = {"Authorization": f"Bearer {get_token()}"}

response_listjobs = requests.get(url_listjobs, headers=headers)
jobsdata = response_listjobs.json()

In [31]:
job_ids = [job['job_id'] for job in jobsdata['jobs'] if 'job_id' in job]
print(job_ids[:5])

['258a6ce8-89b2-4553-a81e-0fc3fb5531c8', '006dc292-af1f-4cf7-8d8f-0f99054e284a', '4096d6a9-09e7-4b52-9f01-ccfad8a8d7d9', 'd38d0b64-759a-48e8-984b-a13f5209f949', 'e68cba12-142c-459c-b6ab-630da39ef3c3']

## Listing Job Status

In [38]:
import requests

url = "https://data.apartmentiq.io/apartmentiq/api/v1/bulk_api/jobs/{job_id}"

for x in job_ids[:4]:
    url = f"https://data.apartmentiq.io/apartmentiq/api/v1/bulk_api/jobs/{x}"
    response = requests.get(url, headers=headers)
    response_print = response.json()
    print(f'Job ID: {response_print['job_id']}')
    print(f'Status: {response_print['status']}')
    print(f'Error message: {response_print['error_message']}')

Job ID: 258a6ce8-89b2-4553-a81e-0fc3fb5531c8
Status: succeeded
Error message: None
Job ID: 006dc292-af1f-4cf7-8d8f-0f99054e284a
Status: succeeded
Error message: None
Job ID: 4096d6a9-09e7-4b52-9f01-ccfad8a8d7d9
Status: succeeded
Error message: None
Job ID: d38d0b64-759a-48e8-984b-a13f5209f949
Status: succeeded
Error message: None

# Saving data extracted to S3

only run below, once job status for all jobs submitted is succeeded

If a particularly large job has been submitted - best to download job results https://developers.apartmentiq.io/api-reference/bulk-data-export/download-batch-job-results

In [39]:
import io

final_df = pd.DataFrame()
for i in range(4):
    url_results_job = "https://data.apartmentiq.io/apartmentiq/api/v1/bulk_api/jobs/"+ job_ids[i] + "/results"
    headers = {"Authorization": f"Bearer {get_token()}"}
    response_prop = requests.get(url_results_job, headers=headers)
    df_prop= pd.read_csv(io.StringIO(response_prop.text), on_bad_lines='skip')
    print(df_prop)
    final_df = pd.concat([final_df,df_prop],axis=0)

        report_generation_date  market_id  \
0                   2025-06-14      93676
1                   2025-06-14      93676
2                   2025-06-14      93676
3                   2025-06-14      93676
4                   2025-06-14      94229
...                        ...        ...
1912501             2026-06-16      94266
1912502             2026-06-16      93676
1912503             2026-06-16      93676
1912504             2026-06-16      93741
1912505             2026-06-16      93561

                                             market_name  property_id  \
0          Chicago-Naperville-Elgin, IL-IN-WI Metro Area     99031039
1          Chicago-Naperville-Elgin, IL-IN-WI Metro Area     99031039
2          Chicago-Naperville-Elgin, IL-IN-WI Metro Area     99031039
3          Chicago-Naperville-Elgin, IL-IN-WI Metro Area     99031039
4        Riverside-San Bernardino-Ontario, CA Metro Area     99006163
...                                                  ...          ...
1912501    San Diego-Chula Vista-Carlsbad, CA Metro Area    100191959
1912502    Chicago-Naperville-Elgin, IL-IN-WI Metro Area     99030989
1912503    Chicago-Naperville-Elgin, IL-IN-WI Metro Area     99030989
1912504            Denver-Aurora-Lakewood, CO Metro Area     99076008
1912505  Atlanta-Sandy Springs-Alpharetta, GA Metro Area     99067580

                         property_name  \
0                           444 Social
1                           444 Social
2                           444 Social
3                           444 Social
4                   The Park at Rancho
...                                ...
1912501           Metro Mission Valley
1912502                           NEXT
1912503                           NEXT
1912504  Millennium Green Valley Ranch
1912505         The Park at Greatstone

                                              property_url  \
0                               https://www.444social.com/
1                               https://www.444social.com/
2                               https://www.444social.com/
3                               https://www.444social.com/
4                  https://www.parkapartmentsatrancho.com/
...                                                    ...
1912501  https://www.windsorcommunities.com/properties/...
1912502                          https://www.nextapts.com/
1912503                          https://www.nextapts.com/
1912504        https://www.millenniumgreenvalleyranch.com/
1912505               https://www.theparkatgreatstone.com/

                        address              city state  zip_code  ...  \
0                444 Parkway Dr      Lincolnshire    IL     60069  ...
1                444 Parkway Dr      Lincolnshire    IL     60069  ...
2                444 Parkway Dr      Lincolnshire    IL     60069  ...
3                444 Parkway Dr      Lincolnshire    IL     60069  ...
4             8255 Vineyard Ave  Rancho Cucamonga    CA     91730  ...
...                         ...               ...   ...       ...  ...
1912501  5080 Camino Del Arroyo         San Diego    CA     92108  ...
1912502       347 W Chestnut St           Chicago    IL     60610  ...
1912503       347 W Chestnut St           Chicago    IL     60610  ...
1912504     4909 N Telluride St            Denver    CO     80249  ...
1912505       1700 Weatherly Dr    Stone Mountain    GA     30083  ...

         concessions  concession_details         last_change_date  \
0                NaN                 NaN                      NaN
1                NaN                 NaN                      NaN
2                NaN                 NaN                      NaN
3                NaN                 NaN               2025-06-04
4                NaN                 NaN               2025-06-12
...              ...                 ...                      ...
1912501       2359.0                 NaN  2026-06-07 04:10:43 UTC
1912502          NaN                 NaN  2026-05-19 00:00:00 UTC
1912503          NaN                 NaN  2026-06-02 00:00:00 UTC
1912504          NaN                 NaN                      NaN
1912505          NaN                 NaN                      NaN

         last_change_amount  total_change_amount rent_change_count  \
0                       NaN                  NaN                 0
1                       NaN                  NaN                 0
2                       NaN                  NaN                 0
3                       NaN                  NaN                 1
4                       NaN                  NaN                84
...                     ...                  ...               ...
1912501                 NaN                  NaN                26
1912502                 NaN                  NaN                16
1912503                 NaN                  NaN                 8
1912504                 NaN                  NaN                 0
1912505                 NaN                  NaN                 0

        trucomp_flag trucomp_rent_diff_pct  trucomp_sq_ft_diff_pct  \
0              False                   NaN                     NaN
1              False                   NaN                     NaN
2              False                   NaN                     NaN
3              False                   NaN                     NaN
4              False                   NaN                     NaN
...              ...                   ...                     ...
1912501        False                   NaN                     NaN
1912502        False                   NaN                     NaN
1912503        False                   NaN                     NaN
1912504        False                   NaN                     NaN
1912505        False                   NaN                     NaN

         trucomp_rent_psf_diff_pct
0                              NaN
1                              NaN
2                              NaN
3                              NaN
4                              NaN
...                            ...
1912501                        NaN
1912502                        NaN
1912503                        NaN
1912504                        NaN
1912505                        NaN

[1912506 rows x 41 columns]
        report_generation_date  market_id  \
0                   2025-06-14      94012
1                   2025-06-14      94012
2                   2025-06-14      94288
3                   2025-06-14      94288
4                   2025-06-14      94288
...                        ...        ...
2000746             2026-06-16      93561
2000747             2026-06-16      94012
2000748             2026-06-16      93672
2000749             2026-06-16      93672
2000750             2026-06-16      93741

                                             market_name  property_id  \
0          Los Angeles-Long Beach-Anaheim, CA Metro Area     99106291
1          Los Angeles-Long Beach-Anaheim, CA Metro Area     99106291
2                 Seattle-Tacoma-Bellevue, WA Metro Area    100517115
3                 Seattle-Tacoma-Bellevue, WA Metro Area    100517115
4                 Seattle-Tacoma-Bellevue, WA Metro Area    100517115
...                                                  ...          ...
2000746  Atlanta-Sandy Springs-Alpharetta, GA Metro Area     99065156
2000747    Los Angeles-Long Beach-Anaheim, CA Metro Area     99032258
2000748     Charlotte-Concord-Gastonia, NC-SC Metro Area     99001828
2000749     Charlotte-Concord-Gastonia, NC-SC Metro Area     99001828
2000750            Denver-Aurora-Lakewood, CO Metro Area    100521333

                      property_name  \
0        The Village at Toluca Lake
1        The Village at Toluca Lake
2         Copal Bellevue Apartments
3         Copal Bellevue Apartments
4         Copal Bellevue Apartments
...                             ...
2000746       Mira at Midtown Union
2000747     Millennium Santa Monica
2000748                  Loft One35
2000749                  Loft One35
2000750         Alexan Pena Station

                                              property_url  \
0        https://www.essexapartmenthomes.com/apartments...
1        https://www.essexapartmenthomes.com/apartments...
2                               https://copalbellevue.com/
3                               https://copalbellevue.com/
4                               https://copalbellevue.com/
...                                                    ...
2000746                      https://miramidtownunion.com/
2000747                 https://millenniumsantamonica.com/
2000748                     https://thecarsonsouthend.com/
2000749                     https://thecarsonsouthend.com/
2000750                     https://alexanpenastation.com/

                       address          city state  zip_code  ...  \
0              211 N Valley St       Burbank    CA     91505  ...
1              211 N Valley St       Burbank    CA     91505  ...
2             13166 NE 15th St      Bellevue    WA     98005  ...
3             13166 NE 15th St      Bellevue    WA     98005  ...
4             13166 NE 15th St      Bellevue    WA     98005  ...
...                        ...           ...   ...       ...  ...
2000746      1301 Spring St NW       Atlanta    GA     30309  ...
2000747  2929 Pennsylvania Ave  Santa Monica    CA     90404  ...
2000748      135 W Morehead St     Charlotte    NC     28202  ...
2000749      135 W Morehead St     Charlotte    NC     28202  ...
2000750       18400 E 64th Ave        Denver    CO     80249  ...

         concessions  concession_details         last_change_date  \
0              600.0                 NaN               2025-06-11
1              600.0                 NaN               2025-06-11
2                NaN                 NaN                      NaN
3                NaN                 NaN               2025-05-09
4                NaN                 NaN               2025-05-10
...              ...                 ...                      ...
2000746      15540.0                 NaN                      NaN
2000747       5904.0                 NaN                      NaN
2000748       2332.0                 NaN                      NaN
2000749       3133.0                 NaN  2026-06-05 00:00:00 UTC
2000750       6669.0                 NaN  2026-04-25 00:00:00 UTC

         last_change_amount  total_change_amount rent_change_count  \
0                       NaN                  NaN                 1
1                       NaN                  NaN                 1
2                       NaN                  NaN                 0
3                       NaN                  NaN                 1
4                       NaN                  NaN                 2
...                     ...                  ...               ...
2000746                 NaN                  NaN                 0
2000747                 NaN                  NaN                 0
2000748                 NaN                  NaN                 0
2000749                 NaN                  NaN                13
2000750                 NaN                  NaN                 1

        trucomp_flag trucomp_rent_diff_pct  trucomp_sq_ft_diff_pct  \
0              False                   NaN                     NaN
1              False                   NaN                     NaN
2              False                   NaN                     NaN
3              False                   NaN                     NaN
4              False                   NaN                     NaN
...              ...                   ...                     ...
2000746        False                   NaN                     NaN
2000747        False                   NaN                     NaN
2000748        False                   NaN                     NaN
2000749        False                   NaN                     NaN
2000750        False                   NaN                     NaN

         trucomp_rent_psf_diff_pct
0                              NaN
1                              NaN
2                              NaN
3                              NaN
4                              NaN
...                            ...
2000746                        NaN
2000747                        NaN
2000748                        NaN
2000749                        NaN
2000750                        NaN

[2000751 rows x 41 columns]
        report_generation_date  market_id  \
0                   2025-06-14      93618
1                   2025-06-14      93618
2                   2025-06-14      93618
3                   2025-06-14      93618
4                   2025-06-14      93618
...                        ...        ...
2215219             2026-06-16      93676
2215220             2026-06-16      94409
2215221             2026-06-16      94409
2215222             2026-06-16      93561
2215223             2026-06-16      93618

                                               market_name  property_id  \
0                Boston-Cambridge-Newton, MA-NH Metro Area     99001172
1                Boston-Cambridge-Newton, MA-NH Metro Area     99001172
2                Boston-Cambridge-Newton, MA-NH Metro Area     99001172
3                Boston-Cambridge-Newton, MA-NH Metro Area     99001172
4                Boston-Cambridge-Newton, MA-NH Metro Area     99001172
...                                                    ...          ...
2215219      Chicago-Naperville-Elgin, IL-IN-WI Metro Area     99084786
2215220  Washington-Arlington-Alexandria, DC-VA-MD-WV M...     99011476
2215221  Washington-Arlington-Alexandria, DC-VA-MD-WV M...     99011473
2215222    Atlanta-Sandy Springs-Alpharetta, GA Metro Area     99084959
2215223          Boston-Cambridge-Newton, MA-NH Metro Area    100184700

                property_name  \
0        Proto Kendall Square
1        Proto Kendall Square
2        Proto Kendall Square
3        Proto Kendall Square
4        Proto Kendall Square
...                       ...
2215219           868 N Wells
2215220          Sedona Slate
2215221          The Palatine
2215222  The Grace Residences
2215223    Pier 7 Development

                                              property_url  \
0                              https://protokendallsq.com/
1                              https://protokendallsq.com/
2                              https://protokendallsq.com/
3                              https://protokendallsq.com/
4                              https://protokendallsq.com/
...                                                    ...
2215219                         https://868northwells.com/
2215220                      https://www.sedona-slate.com/
2215221                      https://www.palatineapts.com/
2215222                    https://thegraceresidences.com/
2215223  https://verisresidential.com/east-boston-ma-ap...

                     address       city state  zip_code  ...  concessions  \
0                 88 Ames St  Cambridge    MA      2142  ...          NaN
1                 88 Ames St  Cambridge    MA      2142  ...          NaN
2                 88 Ames St  Cambridge    MA      2142  ...          NaN
3                 88 Ames St  Cambridge    MA      2142  ...          NaN
4                 88 Ames St  Cambridge    MA      2142  ...          NaN
...                      ...        ...   ...       ...  ...          ...
2215219       868 N Wells St    Chicago    IL     60610  ...          NaN
2215220  1510 Clarendon Blvd  Arlington    VA     22209  ...          NaN
2215221       1301 N Troy St  Arlington    VA     22201  ...          NaN
2215222      200 Nerem St NW    Atlanta    GA     30313  ...       5049.0
2215223          50 Lewis St     Boston    MA      2113  ...          NaN

         concession_details         last_change_date  last_change_amount  \
0                       NaN               2025-06-11                 NaN
1                       NaN               2025-06-14                 NaN
2                       NaN               2025-06-12                 NaN
3                       NaN               2025-06-11                 NaN
4                       NaN               2025-06-11                 NaN
...                     ...                      ...                 ...
2215219                 NaN  2026-06-02 00:00:00 UTC                 NaN
2215220                 NaN                      NaN                 NaN
2215221                 NaN                      NaN                 NaN
2215222                 NaN  2026-06-07 08:20:20 UTC                 NaN
2215223                 NaN  2026-05-29 00:00:00 UTC                 NaN

         total_change_amount rent_change_count trucomp_flag  \
0                        NaN               5.0        False
1                        NaN              41.0        False
2                        NaN              14.0        False
3                        NaN              24.0        False
4                        NaN               8.0        False
...                      ...               ...          ...
2215219                  NaN               9.0        False
2215220                  NaN               0.0        False
2215221                  NaN               0.0        False
2215222                  NaN               5.0        False
2215223                  NaN               1.0        False

        trucomp_rent_diff_pct  trucomp_sq_ft_diff_pct  \
0                         NaN                     NaN
1                         NaN                     NaN
2                         NaN                     NaN
3                         NaN                     NaN
4                         NaN                     NaN
...                       ...                     ...
2215219                   NaN                     NaN
2215220                   NaN                     NaN
2215221                   NaN                     NaN
2215222                   NaN                     NaN
2215223                   NaN                     NaN

         trucomp_rent_psf_diff_pct
0                              NaN
1                              NaN
2                              NaN
3                              NaN
4                              NaN
...                            ...
2215219                        NaN
2215220                        NaN
2215221                        NaN
2215222                        NaN
2215223                        NaN

[2215224 rows x 41 columns]
        report_generation_date  market_id  \
0                   2025-06-14      94121
1                   2025-06-14      94121
2                   2025-06-14      94121
3                   2025-06-14      94121
4                   2025-06-14      94121
...                        ...        ...
2061441             2026-06-16      93561
2061442             2026-06-16      94121
2061443             2026-06-16      94179
2061444             2026-06-16      94229
2061445             2026-06-16      93561

                                              market_name  property_id  \
0        New York-Newark-Jersey City, NY-NJ-PA Metro Area     99010624
1        New York-Newark-Jersey City, NY-NJ-PA Metro Area     99010624
2        New York-Newark-Jersey City, NY-NJ-PA Metro Area     99010624
3        New York-Newark-Jersey City, NY-NJ-PA Metro Area     99010624
4        New York-Newark-Jersey City, NY-NJ-PA Metro Area     99010624
...                                                   ...          ...
2061441   Atlanta-Sandy Springs-Alpharetta, GA Metro Area     99000496
2061442  New York-Newark-Jersey City, NY-NJ-PA Metro Area     99045420
2061443              Phoenix-Mesa-Chandler, AZ Metro Area     99082520
2061444   Riverside-San Bernardino-Ontario, CA Metro Area     99078325
2061445   Atlanta-Sandy Springs-Alpharetta, GA Metro Area     99018770

                      property_name                        property_url  \
0        Riverbend at Port Imperial        https://www.riverbendpi.com/

In [48]:
int_cols_with_nas = [
    "year_built",
    "year_renovated",
    "sq_ft",
    "rent_change_count",
    "row_index",
]
for col in int_cols_with_nas:
    if col in final_df.columns:
        final_df[col] = final_df[col].astype("Int64")

if "zip_code" in final_df.columns:
    final_df["zip_code"] = (
        final_df["zip_code"]
        .fillna("")
        .astype(str)
        .str.replace(r"\.0$", "", regex=True)
    )

if "concession_details" in final_df.columns:
    final_df["concession_details"] = final_df["concession_details"].fillna("")

print("Pandas schema cleanup complete!")

Pandas schema cleanup complete!

In [ ]:
import boto3
s3_client = boto3.client('s3')
bucket_name = 'apartmentiq-region1'
s3_file_key = 'units-raw-history/2025units.csv'

# 4. Save DataFrame to an in-memory buffer, then upload directly to S3
csv_buffer = io.StringIO()
final_df.to_csv(csv_buffer, index=False)

s3_client.put_object(
    Bucket=bucket_name, 
    Key=s3_file_key, 
    Body=csv_buffer.getvalue()
)

print(f"Successfully saved file to s3://{bucket_name}/{s3_file_key}")

In [51]:
final_df[final_df['unit_code'] == '99083916_MFTEIncomeRestrictedSEDUModernStudioApartmentwithInUnitWasherDryerGarageParkingPetFriendlyLivingTournow']

,report_generation_date,market_id,market_name,property_id,property_name,property_url,address,city,state,zip_code,...,concessions,concession_details,last_change_date,last_change_amount,total_change_amount,rent_change_count,trucomp_flag,trucomp_rent_diff_pct,trucomp_sq_ft_diff_pct,trucomp_rent_psf_diff_pct
1826045,2026-06-02,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1830898,2026-06-03,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1840158,2026-06-04,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1842810,2026-06-05,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1849087,2026-06-06,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1856565,2026-06-07,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1861694,2026-06-08,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1867856,2026-06-09,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1874692,2026-06-10,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1881375,2026-06-11,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1882373,2026-06-12,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1892250,2026-06-13,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1897228,2026-06-14,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1905364,2026-06-15,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN
1910342,2026-06-16,94288,"Seattle-Tacoma-Bellevue, WA Metro Area",99083916,Flow Eastlake Apartments,https://www.floweastlake.com/,3150 Fairview Ave E,Seattle,WA,98102,...,NaN,,NaN,NaN,NaN,0,False,NaN,NaN,NaN